# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c159fd389537017661c69a087f60cedbb12be2739f50660cf15c30b743a55cf0e7e05f6b7c2c34804e658324c1ffb5bb8f893543cf5a1a7fcde2600537787bf

test:
  secret_key_base: e330e5a7a28045c74dc4bc588e5630b51d7a5527dd88a1a00f46e00198887f30aa7d0acd4e96adb9a2aef14db2e27dc9c27106c1fa28cd2f993a1ad8eefccc85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0c159fd389537017661c69a087f60cedbb12be2739f50660cf15c30b743a55cf0e7e05f6b7c2c34804e658324c1ffb5bb8f893543cf5a1a7fcde2600537787bf #<%= ENV["SECRET_KEY_BASE"] %>
